### ISSUE TITLE
Template exception handing is broken when rendering a block

### ISSUE THREAD

**Issue by danielkeller** [clokep/django-render-block#47] opened 2023-08-27 08:26 UTC
When I render a block which causes an exception to be thrown (eg `NoReverseMatch` from `{% url %}`), I get a nested exception `'NoneType' object has no attribute 'origin'` from the except block in django/template/base.py, line 974, in render_annotated. This becomes the "main" exception shown at the top of the page, making the issue harder to debug.

I'm using django 4.2.3 and python 3.11.

**Comment by yaakovLowenstein** [comment] 2024-07-01 16:15
@clokep I think this is solved by https://github.com/clokep/django-render-block/pull/52. (I didn't notice this issue prior to opening mine)

**Comment by clokep** [comment] 2024-07-01 16:46
Good call, this is a duplicate of #51.

**Closed** 2024-07-01 16:46 UTC
