### ISSUE TITLE
Inheritance more than one level seems to not work

### ISSUE THREAD

**Issue by deepakkt** [clokep/django-render-block#16] opened 2018-12-31 16:26 UTC
I have three templates

Template A
Template B
Template C

B inherits from A and C inherits from B.

If there is a block in A which I don't specify in C, but try to render the block passing C, it throws a block not found exception.

But it works if I pass in B instead of C.

**Comment by jribbens** [comment] 2023-07-12 13:53
Yes, this has just bitten me.

**Comment by clokep** [comment] 2024-06-28 17:53
I think that #56 might fix this, but would be curious for more real world testing!

**Comment by clokep** [comment] 2024-06-28 17:54
Duplicate of #12.

**Closed by clokep** 2024-06-28 17:54 UTC
